export default {
    LOGIN: '/auth/signin',
    USERS:'/users',
    CHANGE_PASSWORD: '/changePass',
    TYPE_PET: '/types',
    ADD_TYPE_PET: '/insert',
    NO_LOGIN: '/nologin',
    PET: '/pets',
    TRASH: '/trash',
    RESTORE: '/restore',
    PET_SCHEDULE: '/petSchedule',
    SERVICES: '/services',
    SERVICE: '/service',
    ADD_SERVICE: '/insert',
    REGISTERED: '/registered',
    BOOKING_SERVICE: '/bookingService',
    APPROVE: '/approve',
    COMPLETE: '/complete',
    CANCEL: '/cancel',
    VETERINARIANS: '/veterinarians',
};
